name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_site:
    runs-on: ubuntu-latest

    name: Deploy content
    steps:
    - uses: actions/checkout@v3

    - name: Deploy content
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: www531.your-server.de
        protocol: ftps
        username: ${{ secrets.GHA_HETZNER_CONTENT_FTP_USER }}
        password: ${{ secrets.GHA_HETZNER_CONTENT_FTP_PASS }}
        local-dir: ./
        server-dir: /
        exclude: |
          **/staging/**
          .htaccess
          **/.git*
          **/.git*/**
